############################
##                        ##
## nib9888's picom config ##
##                        ##
############################

##
## General Settings
##


# Set backend
backend = "glx";
experimental-backends = true;

# Enable vsync
vsync = true

# Misc performance options
glx-no-rebind-pixmap = true;

# Set log level
log-level = "warn";

# Set windowtype specific options
wintypes: {
  tooltip = { opacity = 0.75; focus = true };
  dock = { shadow = false; };
  dnd = { shadow = false; };
  popup_menu = { fade=false };
};

# Detect '_NET_WM_OPACITY' on client windows, useful for window managers
# not passing '_NET_WM_OPACITY' of client windows to frame windows.
#
# detect-client-opacity = false
detect-client-opacity = true;


##
## Corners
##


# Set corner radius
corner-radius = 12.0;

# Exclude non-proper windows from rounded corners
rounded-corners-exclude = [
  "class_g     = 'Polybar'",
];


##
## Shadows
##


# Disable shadow
shadow = false;


##
## Fading
##

# Enable fading
fading = true;

# Set fade speed
fade-in-step = 0.12; # Opacity change per step
fade-out-step = 0.12; #        ""
fade-delta = 10; # Time between steps

# Exclude slop from fading, for maim reasons
fade-exclude = [
  "class_g     = 'slop'"
]


##
## Transparency / Opacity
##


# Set opacities for windows active/inactive
inactive-opacity = 0.85;
active-opacity = 0.90;

# Don't make frames too obvious
frame-opacity = 0.7;

# These 'windows' should always be focused
focus-exclude = [
  "class_g     = 'slop'", # maim reasons
  "class_g     = 'XAVA'"
];

# Set opacity manually
opacity-rule = [
  "100:class_g = 'se.llbit.chunky.ui.ChunkyFx'",
  "100:class_g = 'Gimp'",
  "80:class_g  = 'Bar'",             # lemonbar
  "100:class_g = 'slop'",            # maim
  "75:class_g  = 'Rofi'",
  "80:class_g  = 'Polybar'",
  "70:class_g  = 'dmenu'",
];


##
## Background-Blurring
##


# Enable blurring the background of windows
blur-background = true;
blur-background-frame = true;

# Set blur method and options
blur-method = "dual_kawase";
blur-size = 12

# Stop transparent polybar sections from being blurred
blur-background-exclude = [
  "class_g     = 'Polybar'",
  "class_g     = 'Dunst'",
  "class_g     = 'XAVA'"
];


#############
##         ##
##   EOF   ##
##         ##
#############
